In [4]:
import pandas as pd
from sklearn.cluster import KMeans
import numpy as np

In [11]:
data_csv = "data/mlflow/424428458709596400/7e8c61caad4243b68aba831a47405afb/artifacts/MOEAD_sample_2_StoppingByEvaluations_2023-03-13T13-09-56.856069.csv"
X_org = pd.read_csv(data_csv, index_col=0)

In [18]:
X_org.head(20)

t        x1        x2        y1        y2  eval_node_id  \
0   0.850303  0.503929  0.388138  0.601255 -0.601255             0   
1   1.171368 -0.519983  0.900389  0.828282 -0.828282             0   
2   0.146309 -0.431984  0.596143  0.103456 -0.103456             0   
3   0.168720  0.104428 -0.265873  0.119303 -0.119303             0   
4   3.055791 -0.990279  0.906877  2.160770 -2.160770             0   
5   4.350237 -0.213778 -0.950850  3.076082 -3.076082             0   
6   3.515489 -0.774510  0.894168  2.485826 -2.485826             0   
7   1.034738  0.784786  0.421546  0.731671 -0.731671             0   
8   2.888552 -0.963694 -0.784136  2.042515 -2.042515             0   
9   4.883712 -0.342388 -0.459854  3.313470 -3.593142             0   
10  3.697817 -0.375116 -0.058561  2.214300 -3.015202             0   
11  4.146316  0.630416  0.321335  2.897771 -2.966005             0   
12  3.785037  0.784186  0.656589  2.676425 -2.676425             0   
13  2.778643 -0.253583  0.659567  1.903385 -2.026210             0   
14  0.512022  0.576779 -0.900644  0.362054 -0.362054             0   
15  4.077945 -0.096810 -0.828613  2.830809 -2.936276             0   
16  2.311731 -0.770681  0.592002  1.634641 -1.634641             0   
17  2.938789 -0.962617 -0.214469  2.078038 -2.078038             0   
18  2.225791 -0.007544  0.047979  0.906026 -2.241718             0   
19  1.308931 -0.116793 -0.581789  0.712419 -1.138689             0   

   diagonal_length  step     t_org     y_org  
0                0     0  0.850303  0.000000  
1                0     1  1.171368  0.000000  
2                0     2  0.146309  0.000000  
3                0     3  0.168720  0.000000  
4                0     4  3.055791  0.000000  
5                0     5  4.350237  0.000000  
6                0     6  3.515489  0.000000  
7                0     7  1.034738  0.000000  
8                0     8  2.888552  0.000000  
9        [-1. -1.]     9  4.883712 -0.197758  
10       [-1. -1.]    10  3.697817 -0.566323  
11         [1. 1.]    11  4.146316 -0.048249  
12               0    12  3.785037  0.000000  
13       [-1.  1.]    13  2.778643 -0.086851  
14               0    14  0.512022  0.000000  
15       [-1. -1.]    15  4.077945 -0.074577  
16               0    16  2.311731  0.000000  
17               0    17  2.938789  0.000000  
18       [-1.  1.]    18  2.225791 -0.944477  
19       [-1. -1.]    19  1.308931 -0.301418

In [24]:
X = X_org[["t","x1","x2"]].values
Y = X_org[["y1", "y2"]].values

# Create a KMeans object with 3 clusters
kmeans = KMeans(n_clusters=5)

# Fit the data to the KMeans model
kmeans.fit(X)

# Print the centroids of each cluster
print(kmeans.cluster_centers_)
print(kmeans.labels_)

kmeans_y = KMeans(n_clusters=5)
kmeans_y.fit(Y)

print(kmeans_y.cluster_centers_)
print(kmeans_y.labels_)

/Users/conan/opt/anaconda3/envs/benchmark-visualizer/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[[ 4.78434532  0.48804712 -0.11597424]
 [ 0.09782879  0.55531766 -0.6936968 ]
 [ 4.22992216  0.52068465 -0.12496864]
 [ 3.32491437  0.46379309 -0.11192415]
 [ 1.91708751  0.13272669 -0.0166504 ]]
[4 4 1 ... 2 2 2]


/Users/conan/opt/anaconda3/envs/benchmark-visualizer/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[[-20.3512908  -26.63484901]
 [  2.44369652  -3.17859091]
 [-10.74201679 -16.86624295]
 [ -3.50928435  -9.72043696]
 [-15.62497178 -21.75191571]]
[1 1 1 ... 0 0 1]
